#!/usr/bin/env bash
set -euo pipefail

: "${GH_REPO:?GH_REPO is required}"
: "${GITHUB_SHA:?GITHUB_SHA is required}"
: "${RELEASE_BRANCH:?RELEASE_BRANCH is required}"
: "${EXPECTED_PREVIOUS_RELEASE_SHA:?EXPECTED_PREVIOUS_RELEASE_SHA is required}"

write_output() {
    if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
        printf '%s\n' "$1" >> "$GITHUB_OUTPUT"
    fi
}

gh_api_retry() {
    local attempts=${METASEQUOIA_GH_API_MAX_ATTEMPTS:-3}
    local delay=${METASEQUOIA_GH_API_RETRY_DELAY:-2}
    local attempt
    if [[ ! "$attempts" =~ ^[1-9][0-9]*$ || ! "$delay" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
        printf 'Invalid GitHub API retry settings.\n' >&2
        return 2
    fi
    for ((attempt = 1; attempt <= attempts; ++attempt)); do
        if gh api "$@"; then
            return 0
        fi
        if ((attempt < attempts)); then
            printf 'GitHub API request failed (attempt %d/%d); retrying in %ss.\n' "$attempt" "$attempts" "$delay" >&2
            sleep "$delay"
        fi
    done
    return 1
}

if [[ "$RELEASE_BRANCH" != release-please--* ]]; then
    printf 'Refusing to promote a non-Release-Please branch: %s\n' "$RELEASE_BRANCH" >&2
    exit 1
fi
if [[ ! "$GITHUB_SHA" =~ ^[0-9a-f]{40}$ ]]; then
    printf 'Invalid workflow commit: %s\n' "$GITHUB_SHA" >&2
    exit 1
fi
if [[ ! "$EXPECTED_PREVIOUS_RELEASE_SHA" =~ ^[0-9a-f]{40}$ ]]; then
    printf 'Invalid previous Release Please commit: %s\n' "$EXPECTED_PREVIOUS_RELEASE_SHA" >&2
    exit 1
fi

base_sha=$(gh_api_retry "repos/$GH_REPO/git/ref/heads/main" --jq .object.sha)
if [[ "$base_sha" != "$GITHUB_SHA" ]]; then
    printf 'main advanced from %s to %s; refusing stale release promotion.\n' "$GITHUB_SHA" "$base_sha" >&2
    exit 1
fi

head_sha=$(gh_api_retry "repos/$GH_REPO/git/ref/heads/$RELEASE_BRANCH" --jq .object.sha)
if [[ ! "$head_sha" =~ ^[0-9a-f]{40}$ || "$head_sha" == "$base_sha" ]]; then
    printf 'Release Please branch returned an invalid release commit: %s\n' "$head_sha" >&2
    exit 1
fi
if [[ "$head_sha" == "$EXPECTED_PREVIOUS_RELEASE_SHA" ]]; then
    printf 'Release Please did not create a new commit during this workflow run.\n' >&2
    exit 1
fi

commit_json=$(gh_api_retry "repos/$GH_REPO/git/commits/$head_sha")
message=$(jq -er '.message | select(type == "string")' <<< "$commit_json")
parent_count=$(jq -er '.parents | length' <<< "$commit_json")
parent_sha=$(jq -er '.parents[0].sha | select(type == "string")' <<< "$commit_json")
if [[ "$parent_count" != 1 || "$parent_sha" != "$base_sha" ]]; then
    printf 'Release commit is not a single-parent fast-forward from main.\n' >&2
    exit 1
fi
author=$(jq -er '[.author.name, .author.email, .committer.name, .committer.email] | @tsv' <<< "$commit_json")
expected_author=$'github-actions[bot]\t41898282+github-actions[bot]@users.noreply.github.com\tGitHub\tnoreply@github.com'
if [[ "$author" != "$expected_author" ]]; then
    printf 'Release commit was not generated by GitHub Actions.\n' >&2
    exit 1
fi

fetch_file() {
    gh_api_retry "repos/$GH_REPO/contents/$1?ref=$2" --jq .content | base64 --decode
}

base_version=$(fetch_file version.txt "$base_sha")
head_version=$(fetch_file version.txt "$head_sha")
if [[ ! "$base_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ||
      ! "$head_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    printf 'Release version files do not contain plain semantic versions.\n' >&2
    exit 1
fi
IFS=. read -r base_major base_minor base_patch <<< "$base_version"
IFS=. read -r head_major head_minor head_patch <<< "$head_version"
if ((10#$head_major < 10#$base_major ||
     (10#$head_major == 10#$base_major && 10#$head_minor < 10#$base_minor) ||
     (10#$head_major == 10#$base_major && 10#$head_minor == 10#$base_minor && 10#$head_patch <= 10#$base_patch))); then
    printf 'Release version %s does not advance %s.\n' "$head_version" "$base_version" >&2
    exit 1
fi
if [[ "$message" != "chore(main): release $head_version" ]]; then
    printf 'Unexpected Release Please commit message: %s\n' "$message" >&2
    exit 1
fi

compare_json=$(gh_api_retry "repos/$GH_REPO/compare/$base_sha...$head_sha")
if [[ "$(jq -er .status <<< "$compare_json")" != ahead || \
      "$(jq -er .ahead_by <<< "$compare_json")" != 1 || \
      "$(jq -er .behind_by <<< "$compare_json")" != 0 ]]; then
    printf 'Release branch is not exactly one commit ahead of main.\n' >&2
    exit 1
fi

files_match=$(jq -r '
    ([.files[].filename] | sort) ==
    ([".release-please-manifest.json", "CHANGELOG.md", "CMakeLists.txt", "version.txt"] | sort)
' <<< "$compare_json")
if [[ "$files_match" != true ]]; then
    printf 'Release commit changed an unexpected file set.\n' >&2
    exit 1
fi

base_manifest=$(fetch_file .release-please-manifest.json "$base_sha")
head_manifest=$(fetch_file .release-please-manifest.json "$head_sha")
if ! jq -e --arg version "$base_version" '.["."] == $version' <<< "$base_manifest" >/dev/null ||
   ! jq -e --arg version "$head_version" '.["."] == $version' <<< "$head_manifest" >/dev/null ||
   [[ "$(jq -cS 'del(.["."])' <<< "$base_manifest")" != "$(jq -cS 'del(.["."])' <<< "$head_manifest")" ]]; then
    printf 'Release Please manifest changed beyond the release version.\n' >&2
    exit 1
fi

base_cmake=$(fetch_file CMakeLists.txt "$base_sha")
head_cmake=$(fetch_file CMakeLists.txt "$head_sha")
base_marker="VERSION $base_version"
head_marker="VERSION $head_version"
cmake_after_marker=${base_cmake#*"$base_marker"}
if [[ "$cmake_after_marker" == "$base_cmake" || "$cmake_after_marker" == *"$base_marker"* ||
      "${base_cmake/$base_marker/$head_marker}" != "$head_cmake" ]]; then
    printf 'CMakeLists.txt changed beyond the project version.\n' >&2
    exit 1
fi

base_changelog=$(fetch_file CHANGELOG.md "$base_sha")
head_changelog=$(fetch_file CHANGELOG.md "$head_sha")
changelog_header=$'# Changelog\n\n'
if [[ "$base_changelog" != "$changelog_header"* || "$head_changelog" != "$changelog_header"* ]]; then
    printf 'Release changelog is missing its stable header.\n' >&2
    exit 1
fi
base_changelog_tail=${base_changelog#"$changelog_header"}
head_changelog_tail=${head_changelog#"$changelog_header"}
if [[ "$head_changelog_tail" != "## [$head_version]"* || "$head_changelog_tail" != *"$base_changelog_tail" ]]; then
    printf 'Release changelog did not prepend the expected version section.\n' >&2
    exit 1
fi

gh workflow run ci-macos.yml --repo "$GH_REPO" --ref "$RELEASE_BRANCH"
max_polls=${METASEQUOIA_RELEASE_CI_MAX_POLLS:-150}
poll_interval=${METASEQUOIA_RELEASE_CI_POLL_INTERVAL:-2}
run_id=""
for ((attempt = 1; attempt <= max_polls; ++attempt)); do
    run_id=$(gh run list --repo "$GH_REPO" --workflow ci-macos.yml --branch "$RELEASE_BRANCH" \
        --event workflow_dispatch --limit 20 --json databaseId,headSha \
        --jq "map(select(.headSha == \"$head_sha\")) | first | .databaseId // empty")
    if [[ -n "$run_id" ]]; then
        break
    fi
    sleep "$poll_interval"
done
if [[ -z "$run_id" ]]; then
    printf 'Timed out waiting for CI to start for release commit %s.\n' "$head_sha" >&2
    exit 1
fi
gh run watch "$run_id" --repo "$GH_REPO" --exit-status --interval 10

current_base_sha=$(gh_api_retry "repos/$GH_REPO/git/ref/heads/main" --jq .object.sha)
current_head_sha=$(gh_api_retry "repos/$GH_REPO/git/ref/heads/$RELEASE_BRANCH" --jq .object.sha)
if [[ "$current_base_sha" != "$base_sha" || "$current_head_sha" != "$head_sha" ]]; then
    printf 'main or the release branch advanced while CI was running; refusing promotion.\n' >&2
    exit 1
fi

gh_api_retry --method PATCH "repos/$GH_REPO/git/refs/heads/main" -f sha="$head_sha" -F force=false >/dev/null
write_output "promoted=true"
write_output "target_sha=$head_sha"
write_output "tag_name=v$head_version"
