#import <AppKit/AppKit.h>

#include <cstdint>
#include <cstddef>
#include <cstring>
#include <vector>

// Community marker protocol (https://nspasteboard.org/) plus password-manager and snippet-tool private types. This set is the twin of MacClipboardCapture.excludedTypes in platforms/macos/src/backend/clipboard/BackendClipboardCapture.swift; keep both lists identical so the input source and the Tauri monitor skip the same copies.
static const char *const kExcludedClipboardTypes[] = {
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "de.petermaurer.TransientPasteboardType",
    "com.typeit4me.clipping",
    "Pasteboard generator type",
    "com.agilebits.onepassword",
};

// Pure predicate over a pasteboard type list: capturable only when plain text is present and no excluded marker type is.
extern "C" bool msime_macos_clipboard_types_capturable(const char *const *types, size_t count) {
    if (!types) return false;
    bool hasString = false;
    for (size_t i = 0; i < count; ++i) {
        const char *type = types[i];
        if (!type) continue;
        if (std::strcmp(type, "public.utf8-plain-text") == 0) hasString = true;
        for (const char *excluded : kExcludedClipboardTypes) {
            if (std::strcmp(type, excluded) == 0) return false;
        }
    }
    return hasString;
}

static bool pasteboardTypesCapturable(NSArray<NSPasteboardType> *types) {
    if (!types) return false;
    std::vector<const char *> names;
    names.reserve(types.count);
    for (NSPasteboardType type in types) {
        const char *name = type.UTF8String;
        if (name) names.push_back(name);
    }
    return msime_macos_clipboard_types_capturable(names.data(), names.size());
}

// Mirrors the source NormalizeClipboardText (server/src/clipboard/clipboard_history.cpp) and client-core `normalize_text`: strip trailing NUL/CR, then keep the first 4000 UTF-16 units without splitting a surrogate pair, so an over-long copy is recorded truncated instead of dropped. The UTF-8 form of 4000 units is at most 12000 bytes, which fits MAX_TEXT_BYTES.
static NSString *normalizedClipboardText(NSString *text) {
    NSUInteger end = text.length;
    while (end > 0) {
        unichar last = [text characterAtIndex:end - 1];
        if (last != 0 && last != '\r') break;
        --end;
    }
    if (end > 4000) {
        end = 4000;
        if (CFStringIsSurrogateHighCharacter([text characterAtIndex:end - 1])) --end;
    }
    return end == text.length ? text : [text substringToIndex:end];
}

static bool copyUTF8(NSString *text, unsigned char *buffer, size_t capacity, size_t *length) {
    NSData *data = [text dataUsingEncoding:NSUTF8StringEncoding];
    if (!data || data.length > capacity) return false;
    if (data.length) std::memcpy(buffer, data.bytes, data.length);
    *length = data.length;
    return true;
}

// Pure entry point over the same normalization, so tests can pin it without touching the general pasteboard.
extern "C" bool msime_macos_normalize_clipboard_text(
    const unsigned char *input,
    size_t inputLength,
    unsigned char *buffer,
    size_t capacity,
    size_t *length) {
    if ((!input && inputLength) || !buffer || !length) return false;
    @autoreleasepool {
        *length = 0;
        NSString *text = [[NSString alloc] initWithBytes:input length:inputLength encoding:NSUTF8StringEncoding];
        if (!text) return false;
        return copyUTF8(normalizedClipboardText(text), buffer, capacity, length);
    }
}

extern "C" bool msime_macos_read_clipboard(
    unsigned char *buffer,
    size_t capacity,
    bool readText,
    size_t *length,
    bool *hasText,
    int64_t *changeCount) {
    if (!buffer || !length || !hasText || !changeCount) return false;
    @autoreleasepool {
        NSPasteboard *pasteboard = NSPasteboard.generalPasteboard;
        if (!pasteboard) return false;
        *length = 0;
        *hasText = false;
        *changeCount = static_cast<int64_t>(pasteboard.changeCount);
        if (!readText) return true;
        // Excluded or text-less changes report hasText=false with the change count set, so the caller advances past them without recording anything.
        if (!pasteboardTypesCapturable(pasteboard.types)) return true;
        NSString *text = [pasteboard stringForType:NSPasteboardTypeString];
        // A write that raced the read may not match the types checked above; keep the pre-read count so the next poll sees the newer count and re-reads it.
        if (static_cast<int64_t>(pasteboard.changeCount) != *changeCount) return true;
        if (!text) return true;
        *hasText = copyUTF8(normalizedClipboardText(text), buffer, capacity, length);
        return true;
    }
}
