[package]
name = "msime-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde.workspace = true
msime-client-core = { path = "../../../crates/client-core" }

[lints]
workspace = true
