#import "AISettingsWindow.h"
#import "MSIMEClientSession.h"
#import "AISettingsSnapshot.h"
@implementation MSIMEAISettingsWindow { NSString *_directory; void (^_saved)(NSDictionary *); NSDictionary *_snapshot; NSButton *_enabled; NSPopUpButton *_provider; NSTextField *_model,*_endpoint,*_limit,*_prompt,*_status; }
- (instancetype)initWithDirectory:(NSString *)d saved:(void (^)(NSDictionary *))s { if((self=[super initWithWindow:nil])){_directory=[d copy];_saved=[s copy];}return self; }
- (void)loadWindow { NSWindow *w=[[NSWindow alloc]initWithContentRect:NSMakeRect(0,0,560,430) styleMask:NSWindowStyleMaskTitled|NSWindowStyleMaskClosable backing:NSBackingStoreBuffered defer:NO];w.title=@"AI 联想设置";self.window=w;_enabled=[NSButton checkboxWithTitle:@"启用 AI 联想" target:nil action:nil];_provider=[[NSPopUpButton alloc]initWithFrame:NSZeroRect];[_provider addItemsWithTitles:@[@"DeepSeek",@"OpenAI",@"SiliconFlow",@"Groq"]];_model=[NSTextField textFieldWithString:@""];_endpoint=[NSTextField textFieldWithString:@""];_limit=[NSTextField textFieldWithString:@"3"];_prompt=[NSTextField textFieldWithString:@""];NSGridView *g=[NSGridView gridViewWithViews:@[@[[NSTextField labelWithString:@"状态"],_enabled],@[[NSTextField labelWithString:@"提供商"],_provider],@[[NSTextField labelWithString:@"模型"],_model],@[[NSTextField labelWithString:@"接口地址"],_endpoint],@[[NSTextField labelWithString:@"候选数量"],_limit],@[[NSTextField labelWithString:@"提示词"],_prompt]]];g.rowSpacing=12;for(NSView *v in @[_model,_endpoint,_limit,_prompt])v.translatesAutoresizingMaskIntoConstraints=NO,[v.widthAnchor constraintEqualToConstant:360].active=YES;NSButton *save=[NSButton buttonWithTitle:@"保存" target:self action:@selector(save:)];NSButton *reload=[NSButton buttonWithTitle:@"重新加载" target:self action:@selector(reload:)];_status=[NSTextField wrappingLabelWithString:@""];NSStackView *s=[NSStackView stackViewWithViews:@[g,_status,[NSStackView stackViewWithViews:@[reload,save]]]];s.orientation=NSUserInterfaceLayoutOrientationVertical;s.spacing=16;s.translatesAutoresizingMaskIntoConstraints=NO;[w.contentView addSubview:s];[NSLayoutConstraint activateConstraints:@[[s.leadingAnchor constraintEqualToAnchor:w.contentView.leadingAnchor constant:20],[s.trailingAnchor constraintEqualToAnchor:w.contentView.trailingAnchor constant:-20],[s.topAnchor constraintEqualToAnchor:w.contentView.topAnchor constant:20]]];[w center]; }
- (void)showWindow:(id)sender {if(!self.window)[self loadWindow];[super showWindow:sender];[self reload:nil];}
- (void)reload:(id)sender {(void)sender;if(!_directory.isAbsolutePath){_status.stringValue=@"请先激活输入法。";return;}_snapshot=[MSIMEClientSession loadPreferencesInDirectory:_directory error:nil];NSDictionary *a=_snapshot[@"preferences"][@"ai_assistant"];_enabled.state=[a[@"enabled"]boolValue]?NSControlStateValueOn:NSControlStateValueOff;NSArray *p=@[@"deepseek",@"openai",@"siliconflow",@"groq"];NSUInteger i=[p indexOfObject:a[@"provider"]];[_provider selectItemAtIndex:i==NSNotFound?0:i];_model.stringValue=a[@"model"]?:@"";_endpoint.stringValue=a[@"endpoint"]?:@"";_limit.stringValue=[a[@"candidate_limit"]stringValue]?:@"3";_prompt.stringValue=a[@"prompt"]?:@"";_status.stringValue=_snapshot?@"修改后点击保存。":@"加载失败。";}
- (void)save:(id)sender {(void)sender;if(!_snapshot)return;NSInteger n=_limit.integerValue;if(n<1||n>10){_status.stringValue=@"候选数量必须为 1～10。";return;}NSArray *p=@[@"deepseek",@"openai",@"siliconflow",@"groq"];NSDictionary *edits=@{ @"enabled":@(_enabled.state==NSControlStateValueOn),@"provider":p[_provider.indexOfSelectedItem],@"model":_model.stringValue, @"endpoint":_endpoint.stringValue,@"candidate_limit":@(n),@"prompt":_prompt.stringValue};NSMutableDictionary *s=[_snapshot mutableCopy];s[@"preferences"]=MSIMEAISettingsMerge(_snapshot[@"preferences"], edits);NSDictionary *saved=[MSIMEClientSession savePreferencesInDirectory:_directory expectedRevision:[_snapshot[@"revision"]unsignedLongLongValue] snapshot:s error:nil];if(saved){_snapshot=saved;_status.stringValue=@"已保存。";if(_saved)_saved(saved[@"preferences"]);}else _status.stringValue=@"保存失败，请重新加载。";}
@end
