import AppKit

@MainActor protocol MacClipboardSource {
  var changeCount: Int { get }
  var types: [NSPasteboard.PasteboardType]? { get }
  func text() -> String?
}

@MainActor struct MacPasteboardSource: MacClipboardSource {
  let pasteboard: NSPasteboard
  var changeCount: Int { pasteboard.changeCount }
  var types: [NSPasteboard.PasteboardType]? { pasteboard.types }
  func text() -> String? { pasteboard.string(forType: .string) }
}

/// Sampling only: the host owns scheduling, shared enablement and persistence.
/// No contents are retained here. A failed save can retry the same clipboard change.
@MainActor final class MacClipboardCapture {
  struct Sample: Sendable {
    let text: String
    fileprivate let sequence: Int
    fileprivate let generation: UInt64
  }

  // Community marker protocol: https://nspasteboard.org/
  static let excludedTypes: Set<String> = [
    "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType", "de.petermaurer.TransientPasteboardType",
    "com.typeit4me.clipping", "Pasteboard generator type", "com.agilebits.onepassword"
  ]
  private let source: any MacClipboardSource
  private var lastSequence: Int?
  private var offeredSequence: Int?
  private var generation: UInt64 = 0

  init(source: any MacClipboardSource) { self.source = source }

  func sample(enabled: Bool) -> Sample? {
    guard enabled else {
      lastSequence = nil
      offeredSequence = nil
      generation &+= 1
      return nil
    }
    let sequence = source.changeCount
    guard let previous = lastSequence else {
      // Match Windows monitor startup: never import pre-existing clipboard text.
      lastSequence = sequence
      return nil
    }
    guard sequence != previous, let types = source.types else { return nil }
    if !types.contains(.string) || types.contains(where: { Self.excludedTypes.contains($0.rawValue) }) {
      lastSequence = sequence
      offeredSequence = nil
      return nil
    }
    guard let text = source.text(), source.changeCount == sequence else { return nil }
    guard !text.isEmpty, text.utf8.count <= 4096,
          !text.unicodeScalars.contains(where: {
            ($0.value < 32 && ![9, 10, 13].contains($0.value)) || (127...159).contains($0.value)
          }) else {
      lastSequence = sequence
      offeredSequence = nil
      return nil
    }
    offeredSequence = sequence
    return Sample(text: text, sequence: sequence, generation: generation)
  }

  func acknowledge(_ sample: Sample) {
    guard sample.generation == generation, sample.sequence == offeredSequence else { return }
    lastSequence = sample.sequence
    offeredSequence = nil
  }
}
