#import "CloudClipboardWindowController.h"
#import "CloudClipboardClient.h"
@implementation MSIMECloudClipboardWindowController { NSString *_token; NSTextView *_editor; NSTextField *_search; NSTextView *_items; NSTextField *_status; }
+ (instancetype)sharedController { static MSIMECloudClipboardWindowController *c; static dispatch_once_t once; dispatch_once(&once, ^{ c=[self new]; }); return c; }
- (void)showWithToken:(NSString *)token { _token=[token copy]; if(!self.window){self.window=[[NSWindow alloc]initWithContentRect:NSMakeRect(0,0,480,420) styleMask:(NSWindowStyleMaskTitled|NSWindowStyleMaskClosable) backing:NSBackingStoreBuffered defer:NO];self.window.title=@"云剪贴板";} _items=[[NSTextView alloc]initWithFrame:NSMakeRect(20,180,440,210)];_items.editable=NO;_items.font=[NSFont systemFontOfSize:13]; _editor=[[NSTextView alloc]initWithFrame:NSMakeRect(20,100,440,70)]; _search=[[NSTextField alloc]initWithFrame:NSMakeRect(20,65,300,24)]; _search.placeholderString=@"搜索云端历史"; NSButton *refresh=[NSButton buttonWithTitle:@"刷新" target:self action:@selector(refresh:)];refresh.frame=NSMakeRect(330,62,70,30); NSButton *copy=[NSButton buttonWithTitle:@"复制选中条目" target:self action:@selector(copyItem:)];copy.frame=NSMakeRect(240,25,120,32); NSButton *upload=[NSButton buttonWithTitle:@"上传明确选择的文本" target:self action:@selector(upload:)];upload.frame=NSMakeRect(20,25,180,32); _status=[[NSTextField alloc]initWithFrame:NSMakeRect(20,0,440,24)];_status.editable=NO;_status.bezeled=NO;_status.drawsBackground=NO; NSView*v=[NSView new];v.frame=NSMakeRect(0,0,480,420);for(NSView*x in @[_items,_editor,_search,refresh,copy,upload,_status])[v addSubview:x];self.window.contentView=v;[self.window center];[self showWindow:nil];[NSApp activateIgnoringOtherApps:YES];[self refresh:nil]; }
- (void)copyItem:(id)sender { (void)sender; NSString *text=_items.string; if(text.length){[[NSPasteboard generalPasteboard] clearContents];[[NSPasteboard generalPasteboard] setString:text forType:NSPasteboardTypeString];_status.stringValue=@"已复制到本机剪贴板";} }
- (void)upload:(id)sender { (void)sender; NSString *text=_editor.string;if(!text.length||text.length>4000)return;MSIMEAddCloudClipboard(text,_token,^(__unused NSData*d,NSInteger s,__unused NSError*e){if(s>=200&&s<300){self->_editor.string=@"";[self refresh:nil];}}); }
- (void)refresh:(id)sender { (void)sender;NSString *q=_search.stringValue?:@"";MSIMEFetchCloudClipboard(q,_token,^(NSData*d,NSInteger s,__unused NSError*e){if(s>=200&&s<300){NSError *jsonError=nil;NSDictionary *root=[NSJSONSerialization JSONObjectWithData:d options:0 error:&jsonError];NSArray *entries=[root isKindOfClass:NSDictionary.class]?root[@"items"]:nil;NSMutableString *text=[NSMutableString string];for(NSDictionary *entry in entries){NSString *value=entry[@"text"];NSString *date=entry[@"created_at"];if([value isKindOfClass:NSString.class])[text appendFormat:@"%@%@\n\n",value,[date isKindOfClass:NSString.class]?[NSString stringWithFormat:@"（%@）",date]:@""];}self->_items.string=text.length?text:@"暂无云端历史";self->_status.stringValue=[NSString stringWithFormat:@"已刷新（%@）",q];}else self->_status.stringValue=@"刷新失败";}); }
@end
