#import "CloudClipboardWindowController.h"
#import "CloudClipboardClient.h"
@implementation MSIMECloudClipboardWindowController { NSString *_token; NSTextView *_editor; NSTextField *_search; NSTextView *_items; NSTextField *_status; NSArray *_entries; }
+ (instancetype)sharedController { static id c; static dispatch_once_t once; dispatch_once(&once, ^{ c=[self new]; }); return c; }
- (void)showWithToken:(NSString *)token { _token=[token copy]; if(!self.window){ self.window=[[NSWindow alloc] initWithContentRect:NSMakeRect(0,0,480,420) styleMask:(NSWindowStyleMaskTitled|NSWindowStyleMaskClosable) backing:NSBackingStoreBuffered defer:NO]; self.window.title=@"云剪贴板"; } _items=[[NSTextView alloc] initWithFrame:NSMakeRect(20,180,440,210)]; _items.editable=NO; _editor=[[NSTextView alloc] initWithFrame:NSMakeRect(20,100,440,70)]; _search=[[NSTextField alloc] initWithFrame:NSMakeRect(20,65,300,24)]; _search.placeholderString=@"搜索云端历史"; NSButton *r=[NSButton buttonWithTitle:@"刷新" target:self action:@selector(refresh:)]; r.frame=NSMakeRect(330,62,70,30); NSButton *d=[NSButton buttonWithTitle:@"删除选中条目" target:self action:@selector(deleteItem:)]; d.frame=NSMakeRect(330,25,120,32); NSButton *u=[NSButton buttonWithTitle:@"上传明确选择的文本" target:self action:@selector(upload:)]; u.frame=NSMakeRect(20,25,180,32); _status=[[NSTextField alloc] initWithFrame:NSMakeRect(20,0,440,24)]; _status.editable=NO; _status.bezeled=NO; _status.drawsBackground=NO; NSView *v=[NSView new]; for(NSView *x in @[_items,_editor,_search,r,d,u,_status]) [v addSubview:x]; self.window.contentView=v; [self.window center]; [self showWindow:nil]; [self refresh:nil]; }
- (void)deleteItem:(id)sender { (void)sender; for(NSDictionary *e in _entries) if([_items.string containsString:e[@"text"]]) { MSIMERemoveCloudClipboard(e[@"id"],_token,^(NSData *d,NSInteger s,NSError *x){(void)d;(void)x;if(s>=200&&s<300)[self refresh:nil];}); return; } _status.stringValue=@"请选择要删除的条目"; }
- (void)upload:(id)sender { (void)sender; NSString *t=_editor.string; if(!t.length||t.length>4000)return; MSIMEAddCloudClipboard(t,_token,^(NSData*d,NSInteger s,NSError*e){(void)d;(void)e;if(s>=200&&s<300)[self refresh:nil];}); }
- (void)refresh:(id)sender { (void)sender; MSIMEFetchCloudClipboard(_search.stringValue?:@"",_token,^(NSData*d,NSInteger s,NSError*e){(void)e;if(s<200||s>=300){self->_status.stringValue=@"刷新失败";return;} NSDictionary *r=[NSJSONSerialization JSONObjectWithData:d options:0 error:nil]; self->_entries=[r isKindOfClass:NSDictionary.class]&&[r[@"items"] isKindOfClass:NSArray.class]?r[@"items"]:@[]; NSMutableString *o=[NSMutableString string]; for(NSDictionary*x in self->_entries) if([x[@"text"] isKindOfClass:NSString.class])[o appendFormat:@"%@\n\n",x[@"text"]]; self->_items.string=o.length?o:@"暂无云端历史"; self->_status.stringValue=@"已刷新";}); }
@end
