#import "VoiceSettings.h"
#import <Security/Security.h>
static NSString *const VoiceService = @"com.houko.inputmethod.MetasequoiaIME.voice";
static NSError *VoiceError(NSString *m) { return [NSError errorWithDomain:VoiceService code:1 userInfo:@{NSLocalizedDescriptionKey:m}]; }
static BOOL SecureEndpoint(NSString *s) { NSURLComponents *u=[NSURLComponents componentsWithString:s]; return [u.scheme.lowercaseString isEqualToString:@"https"] && u.host.length>0 && !u.user && !u.password && !u.fragment; }
static NSString *StringValue(NSDictionary *d, NSString *k, NSString *fallback) { id v=d[k]; return [v isKindOfClass:NSString.class] ? v : fallback; }
static NSString *ReadToken(NSString *kind, NSString *endpoint) { NSString *account=[NSString stringWithFormat:@"%@|%@",kind,endpoint]; NSDictionary *q=@{(__bridge id)kSecClass:(__bridge id)kSecClassGenericPassword,(__bridge id)kSecAttrService:VoiceService,(__bridge id)kSecAttrAccount:account,(__bridge id)kSecReturnData:@YES}; CFTypeRef r=NULL; if(SecItemCopyMatching((__bridge CFDictionaryRef)q,&r)!=errSecSuccess)return @""; return [[NSString alloc] initWithData:CFBridgingRelease(r) encoding:NSUTF8StringEncoding] ?: @""; }
@implementation MetasequoiaVoiceSettings
+ (instancetype)loadSettings { NSDictionary *d=[[NSUserDefaults standardUserDefaults] dictionaryForKey:@"voiceInput"] ?: @{}; MetasequoiaVoiceSettings *s=[self new]; s.provider=StringValue(d,@"provider",@"cloud"); s.endpoint=StringValue(d,@"endpoint",@"https://api.siliconflow.cn/v1/audio/transcriptions"); s.model=StringValue(d,@"model",@"FunAudioLLM/SenseVoiceSmall"); s.modelPath=StringValue(d,@"modelPath",@""); s.polishEndpoint=StringValue(d,@"polishEndpoint",@"https://api.siliconflow.cn/v1/chat/completions"); s.polishModel=StringValue(d,@"polishModel",@"Qwen/Qwen3-8B"); s.polishEnabled=[d[@"polishEnabled"] boolValue]; s.token=ReadToken(@"asr",s.endpoint); s.polishToken=ReadToken(@"polish",s.polishEndpoint); return s; }
- (BOOL)validate:(NSError **)error { NSString *m=nil; if([self.provider isEqualToString:@"local"]){BOOL dir=NO;if(![[NSFileManager defaultManager] fileExistsAtPath:self.modelPath isDirectory:&dir]||dir)m=@"请选择已下载的 Whisper 模型文件。";} else if(![self.provider isEqualToString:@"cloud"]||!SecureEndpoint(self.endpoint)||!self.model.length||!self.token.length)m=@"请填写 HTTPS 识别地址、模型名称和 API 密钥。"; if(self.polishEnabled&&(!SecureEndpoint(self.polishEndpoint)||!self.polishModel.length||!self.polishToken.length))m=@"启用文本整理需要有效的 HTTPS 服务配置。"; if(m){if(error)*error=VoiceError(m);return NO;} return YES; }
- (BOOL)save:(NSError **)error { if(![self validate:error])return NO; [[NSUserDefaults standardUserDefaults] setObject:@{@"provider":self.provider, @"endpoint":self.endpoint, @"model":self.model, @"modelPath":self.modelPath, @"polishEnabled":@(self.polishEnabled), @"polishEndpoint":self.polishEndpoint, @"polishModel":self.polishModel} forKey:@"voiceInput"]; return YES; }
@end
