// Fixed display samples from MSIME-Windows 04a8df56 settings candidate partials.
// These are not user input or candidates generated by the shared runtime.
const samples = [["你们", "rR"], ["你", "rX"], ["尼", "uV"], ["妮", "nV"], ["泥", "dV"], ["逆", "zQ"]] as const;

export function SkinCandidatePreview({ orientation }: { orientation: "horizontal" | "vertical" }) {
  const horizontal = orientation === "horizontal";
  return <div className={`candidate wnd-${horizontal ? "h" : "v"}`} data-preview-layout={orientation}>
    <div className="container">
      <div className="row pinyin"><div className="text">ni'mf<span className="cursor" /></div><div className="hidden-pinyin">n</div></div>
      {samples.map(([text, helpcode], index) => <div key={index} className={`row-wrapper${horizontal && index === 0 ? " first-row-wrapper" : ""}`}>
        <div className={`row cand${index === 0 ? " first" : ""}`}>
          <div className="text">
            <span className={horizontal ? "num" : "cand-no"}>{index + 1}</span>
            {horizontal ? <>{text}<span className="cand-helpcode">({helpcode})</span></> :
              <span className="cand-content">{text}<span className="cand-helpcode">({helpcode})</span></span>}
          </div>
        </div>
      </div>)}
    </div>
  </div>;
}
