import AppKit
import SwiftUI
import Darwin

@MainActor
final class MacClipboardHistoryModel: ObservableObject {
  @Published var items: [ClipboardHistoryItem] = []
  @Published var search = ""
  @Published var message: String?
  private let store: ClipboardHistoryStore
  init(store: ClipboardHistoryStore = ClipboardHistoryStore()) { self.store = store }
  var filtered: [ClipboardHistoryItem] {
    search.isEmpty ? items : items.filter { $0.text.localizedCaseInsensitiveContains(search) }
  }
  // The system pasteboard is read only by this explicit button action.
  func capture(from pasteboard: NSPasteboard = .general) {
    perform {
      let version = pasteboard.changeCount
      guard !Self.excluded(pasteboard) else { throw ServiceFailure(message: "此内容被来源应用标记为敏感、临时或自动生成，未保存。") }
      let text = pasteboard.string(forType: .string) ?? ""
      guard version == pasteboard.changeCount, !Self.excluded(pasteboard) else {
        throw ServiceFailure(message: "剪贴板内容已变化，请重试。")
      }
      try store.add(text)
    }
  }
  // Community pasteboard markers: https://nspasteboard.org/
  private static func excluded(_ pasteboard: NSPasteboard) -> Bool {
    let excluded = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                    "org.nspasteboard.AutoGeneratedType", "de.petermaurer.TransientPasteboardType"]
      .map { NSPasteboard.PasteboardType($0) }
    return pasteboard.availableType(from: excluded) != nil ||
      (pasteboard.pasteboardItems ?? []).contains { !Set($0.types).isDisjoint(with: excluded) }
  }
  func refresh() { perform {} }
  func change(_ id: UUID, delete: Bool) {
    perform {
      var latest = try store.load()
      if delete { latest.removeAll { $0.id == id } }
      else if let index = latest.firstIndex(where: { $0.id == id }) { latest[index].pinned.toggle() }
      try store.save(latest)
    }
  }
  func clear() { perform { try store.save([]) } }
  func copy(_ id: UUID, to pasteboard: NSPasteboard = .general) {
    perform {
      guard let item = try store.load().first(where: { $0.id == id }) else {
        throw ServiceFailure(message: "记录已删除，请刷新后重试。")
      }
      pasteboard.clearContents()
      guard pasteboard.setString(item.text, forType: .string) else {
        throw ServiceFailure(message: "无法写入系统剪贴板，请重试。")
      }
    }
  }
  private func perform(_ action: () throws -> Void) {
    do {
      try FileManager.default.createDirectory(at: store.file.deletingLastPathComponent(), withIntermediateDirectories: true)
      let descriptor = open(store.file.appendingPathExtension("lock").path, O_CREAT | O_RDWR, 0o600)
      guard descriptor >= 0 else { throw ServiceFailure(message: "无法打开本机历史。") }
      defer { Darwin.close(descriptor) }
      guard flock(descriptor, LOCK_EX | LOCK_NB) == 0 else { throw ServiceFailure(message: "历史正在更新，请稍后重试。") }
      defer { flock(descriptor, LOCK_UN) }
      try action()
      items = try store.load(); message = nil
    } catch { items = []; message = error.localizedDescription }
  }
  func close() { items = []; search = ""; message = nil }
}

struct MacClipboardHistoryView: View {
  @ObservedObject var model: MacClipboardHistoryModel
  @State private var confirmingClear = false
  var body: some View {
    VStack(alignment: .leading, spacing: 12) {
      Text("本机剪贴板历史").font(.title2)
      Text("点按保存才会读取当前剪贴板。最多 50 条，仅保存在本机；复制后在目标应用按 ⌘V 粘贴。")
        .font(.footnote).foregroundStyle(.secondary)
      HStack {
        Button("保存当前剪贴板") { model.capture() }
          .accessibilityIdentifier("captureClipboard")
        Button("刷新") { model.refresh() }
        Spacer()
        Text("\(model.items.count) / 50").foregroundStyle(.secondary)
      }
      TextField("搜索历史文字", text: $model.search)
      List(model.filtered) { item in
        VStack(alignment: .leading, spacing: 6) {
          Text(item.text).lineLimit(4).textSelection(.enabled)
          HStack {
            Text(item.date.formatted(date: .abbreviated, time: .shortened)).font(.caption).foregroundStyle(.secondary)
            Spacer()
            Button("复制") { model.copy(item.id) }
            Button(item.pinned ? "取消固定" : "固定") { model.change(item.id, delete: false) }
            Button("删除", role: .destructive) { model.change(item.id, delete: true) }
          }
        }.padding(.vertical, 6)
      }.overlay(Group {
        if model.filtered.isEmpty { Text(model.search.isEmpty ? "暂无历史" : "没有匹配的记录").foregroundStyle(.secondary) }
      })
      if let message = model.message { Text(message).foregroundStyle(.secondary).textSelection(.enabled) }
      Button("清空本机历史…", role: .destructive) { confirmingClear = true }
    }.padding(20).frame(minWidth: 540, minHeight: 420)
      .onAppear { model.refresh() }
      .alert("清空本机剪贴板历史？", isPresented: $confirmingClear) {
        Button("取消", role: .cancel) {}
        Button("清空", role: .destructive) { model.clear() }
      } message: { Text("全部本机记录（包括固定项）将删除，无法撤销。系统剪贴板和云端历史不受影响。") }
  }
}

@MainActor
final class MacClipboardHistoryWindow: NSWindowController, NSWindowDelegate {
  static let shared = MacClipboardHistoryWindow()
  private let model = MacClipboardHistoryModel()
  private init() {
    let window = NSWindow(contentRect: NSRect(x: 0, y: 0, width: 660, height: 600),
                          styleMask: [.titled, .closable, .miniaturizable, .resizable], backing: .buffered, defer: false)
    super.init(window: window)
    window.title = "本机剪贴板历史"; window.isReleasedWhenClosed = false
    window.delegate = self; window.center()
  }
  required init?(coder: NSCoder) { fatalError("init(coder:) has not been implemented") }
  func showHistory() {
    if !(window?.contentView is NSHostingView<MacClipboardHistoryView>) { window?.contentView = NSHostingView(rootView: MacClipboardHistoryView(model: model)) }
    model.refresh(); showWindow(nil); window?.makeKeyAndOrderFront(nil); NSApp.activate(ignoringOtherApps: true)
  }
  func windowDidBecomeKey(_ notification: Notification) { model.refresh() }
  func windowWillClose(_ notification: Notification) { window?.contentView = nil; model.close() }
}

@_cdecl("MSIMEShowClipboardHistory")
func showClipboardHistory() { Task { @MainActor in MacClipboardHistoryWindow.shared.showHistory() } }
