#include "CandidateSkin.h"
#include <cassert>
#include <cmath>
#include <string_view>

using msime::mac::BuiltInSkinTokens;
using msime::mac::Rgba;
static void CheckColor(Rgba value, unsigned rgb, float alpha = 1) {
    assert(std::abs(value.r - ((rgb >> 16) & 255) / 255.f) < 0.00001f);
    assert(std::abs(value.g - ((rgb >> 8) & 255) / 255.f) < 0.00001f);
    assert(std::abs(value.b - (rgb & 255) / 255.f) < 0.00001f);
    assert(std::abs(value.a - alpha) < 0.00001f);
}
int main() {
    // Golden values from Apple b637828 CandidateSkin.cpp, not generated by the resolver.
    struct Fixture { const char *id; bool dark; unsigned surface, text, number, selectedText, accent; float radius, border, pad; bool bar; };
    const Fixture fixtures[] = {
        {"fluent", false, 0xFFFFFF, 0x1A1A1A, 0x1A1A1A, 0x1A1A1A, 0x6B69D6, 6, 1.5, 5, true},
        {"fluent", true, 0x202020, 0xE9E8E8, 0xE9E8E8, 0xE9E8E8, 0x6B69D6, 6, 1.5, 5, true},
        {"wechat", false, 0xF7F7F7, 0x333333, 0x757575, 0xFFFFFF, 0x07C160, 5, 1, 2, false},
        {"wechat", true, 0x151515, 0xB7B7B7, 0x858585, 0xFFFFFF, 0x07C160, 5, 1, 2, false},
        {"graphite", false, 0xFBFBFC, 0x586476, 0x8993A1, 0x111827, 0x5F6B7A, 3, 1, 5, false},
        {"graphite", true, 0x1C1F23, 0xAEB6C2, 0x707987, 0xF1F3F5, 0x8993A0, 3, 1, 5, false},
        {"willow_green", false, 0xF4F5F3, 0x333333, 0x757575, 0xFFFFFF, 0x58B980, 9, 0, 0, false},
        {"willow_green", true, 0x2D2F2E, 0xD8DBD8, 0xA6ABA7, 0xFFFFFF, 0x65C98D, 9, 0, 0, false},
    };
    for (const auto &f : fixtures) {
        const auto t = BuiltInSkinTokens(f.id, f.dark);
        CheckColor(t.surface, f.surface);
        CheckColor(t.text, f.text);
        CheckColor(t.number, f.number, std::string_view(f.id) == "fluent" ? (f.dark ? .616f : .55f) : 1);
        CheckColor(t.selectedText, f.selectedText);
        CheckColor(t.accent, f.accent);
        assert(t.radius == f.radius && t.borderWidth == f.border && t.pad == f.pad && t.showSelectedBar == f.bar);
    }
    CheckColor(BuiltInSkinTokens("fluent", false).selected, 0xE8E8E8);
    CheckColor(BuiltInSkinTokens("fluent", true).selected, 0x3E3E3E, .725f);
    for (bool dark : {false, true}) {
        CheckColor(BuiltInSkinTokens("wechat", dark).selected, 0x07C160);
        CheckColor(BuiltInSkinTokens("graphite", dark).selected, 0, 0);
        CheckColor(BuiltInSkinTokens("willow_green", dark).border, 0, 0);
        CheckColor(BuiltInSkinTokens("unknown", dark).surface, dark ? 0x202020 : 0xFFFFFF);
    }
}
